### ISSUE TITLE
Updates needed to external documents and forked repos

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/chat#19]
## [SDW's MapML Project description](https://github.com/w3c/sdw/projects?query=is%3Aopen#:~:text=Map%20Markup%20Language%20-%20MapML):

> We are holding a [workshop](https://www.w3.org/2020/maps/).

- [x] Change to e.g. "We held a [workshop](https://www.w3.org/2020/maps/), see [the report](https://www.w3.org/2020/maps/report)."

> A pair of evolving draft specifications describing the elements are available: https://maps4html.github.io/HTML-Map-Element/spec/ and https://maps4html.github.io/MapML/spec/

- [x] Change to e.g. "An evolving draft specification describing the elements is available: https://maps4html.github.io/MapML/spec/".

> "An [explainer document](https://www.w3.org/2020/maps/) for the above specifications".

- [x] Probably change link destination of "explainer document" to https://github.com/Maps4HTML/MapML-Proposal

> A demo site (kick the tires!) is available, which more closely tracks the spec evolution

- [x] Maybe remove ", which more closely tracks the spec evolution"

## NRCAN

- [x] The [Maps for HTML Tutorial](https://www.nrcan.gc.ca/science-and-data/science-and-research/earth-sciences/geography/topographic-information/web-services/maps-for-html-tutorial/18875) should replace `<map>` with `<mapml-viewer>`

## "About" descriptions of forked repositories:

[Maps4HTML/geoserver](https://github.com/Maps4HTML/geoserver):

> Maps for HTML Community Module development fork of GeoServer
> [geoserver.org/](http://geoserver.org/)

- [x] Probably change "Maps for HTML Community Module" to "MapML Extension"
- [x] Change link from "geoserver.org/" to "https://docs.geoserver.org/latest/en/user/extensions/mapml/index.html"

<hr>

[Maps4HTML/MapServer-documentation](https://github.com/Maps4HTML/MapServer-documentation):

> Source repository for the MapServer documentation, for the live website. Please submit pull requests to the 'main' branch.
> [mapserver.org](https://mapserver.org/)

- [x] Change description to e.g. "MapML documentation on MapServer"
- [x] Change link from "[mapserver.org](https://mapserver.org/)" to "https://www.mapserver.org/development/rfc/ms-rfc-123.html"

<hr>

[Maps4HTML/TiledArt-Rousseau](https://github.com/Maps4HTML/TiledArt-Rousseau):

- [x] Add description, e.g.: "Resource for examples: https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/tree/master/examples"

<hr>

[Maps4HTML/FiskMississippiMapsStreamCourses](https://github.com/Maps4HTML/FiskMississippiMapsStreamCourses):

- [x] Add description, e.g.: "Resource for examples: https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/tree/master/examples"

**Comment by Malvoz** [comment]
> [Maps for HTML Tutorial](https://www.nrcan.gc.ca/science-and-data/science-and-research/earth-sciences/geography/topographic-information/web-services/maps-for-html-tutorial/18875)

I noticed this web page too has `<map>`: https://www.nrcan.gc.ca/science-and-data/science-and-research/earth-sciences/geography/topographic-information/web-services/17216#g5

**Comment by prushforth** [comment]
I've sent the updates to our content management team. Might take a bit before its updated.

**Comment by Malvoz** [comment]
Okay, we can close this then. Thanks for making these changes!

**Comment by Malvoz** [comment]
@prushforth would you please like to update the https://github.com/Maps4HTML/webwewant.fyi repo description (not any files) from:

> **About**
>
> If you build websites, you inevitably run into problems. Maybe there’s no way to achieve an aspect of your design using CSS. Or maybe there’s a device feature you really wish you could tap into using JavaScript. Or perhaps the in-browser DevTools don’t give you a key insight you need to do your job. We want to hear about it!
>
>🔗 [webwewant.fyi](https://webwewant.fyi/)

to something like:

> Web Want for native maps in the browser
>
>🔗 https://webwewant.fyi/wants/61/

🙏🏼

**Comment by prushforth** [comment]
Lmk if you need me to actually do something

**Comment by Malvoz** [comment]
> Lmk if you need me to actually do something

@prushforth perhaps you misread, because I asked if you could change that forked repo's "About" description. 😋

**Comment by prushforth** [comment]
🤦🏼‍♂️

**Comment by prushforth** [comment]
Changed access so contributors can write. Can't see the description to edit from my phone that won't end up in a PR.

**Comment by Malvoz** [comment]
Changing settings requires [owner access](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository#owner-access-for-a-repository-owned-by-a-user-account), it's nothing urgent though, you can edit it when you find the time.

**Comment by prushforth** [comment]
Gave you admin

**Comment by Malvoz** [comment]
Alright, I've changed the description. Thanks!

**Comment by prushforth** [comment]
Thank you!
