### ISSUE TITLE
Referring to the MapML polyfill consistently, and what to call it

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/chat#21]
We vary in how we refer to the polyfill, mostly it's "Web map custom element" or slight variations thereof, in other cases it's variations of "MapML(-viewer) polyfill".

<details><summary>Examples</summary>

## "Web Map Custom Element" variants:

- https://github.com/orgs/Maps4HTML/projects/1:

  > Web map polyfill development

  (project name)

- https://github.com/Maps4HTML/web-map-doc:
  - > web-map-doc
  
  (repo name)
  
  - > Web-Map-Custom-Element
  
  (in the repo description)
- https://github.com/Maps4HTML/web-map-doc/blob/main/README.md:
  > web-map-element
- https://github.com/Maps4HTML/experiments/blob/main/README.md:
  > Web Map Custom Element polyfill
- https://github.com/Maps4HTML/Web-Map-Custom-Element:
    - > Web-Map-Custom-Element
    
    (repo name)
    - > @maps4html/web-map-custom-element
    
    (package name)
- https://maps4html.org/MapML/spec/#bib-web-map-custom-element:
  > [Web-Map-Custom-Element]
- https://maps4html.org/:
  > Web-map custom element

## "MapML-viewer" variants:

- https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/main/README.md:
  > `<mapml-viewer>` custom element
- https://maps4html.org/UCR-MapML-Matrix/mapml-ucrs-fulfillment-matrix.html:
  > MapML-Viewer custom-component polyfill
- https://github.com/Maps4HTML/mapml-extension:
  > MapML Browser Extension

  (should this rather say MapML _Polyfill_ Browser Extension? Or _MapML-viewer_ Browser Extension?)

<hr>

</details>
  
The name "Web Map Custom Element" makes sense in that we're using custom elements to polyfill a technology that is envisioned to become the standard for "web maps". And in earlier stages there was no `<mapml-viewer>` element, only the `<map is="web-map">` built-in, so that made sense at that point in time.

I thinks it's important that we refer to the polyfill by name consistently. The major difference between the two is that "MapML polyfill"/"MapML-viewer (custom element)" describes the technology that is being polyfilled, which I am in favor of.

WDYT?

In most cases it's straight forward to make the necessary changes, but if we're to go with "MapML polyfill" or "MapML-viewer (custom element)" (depending on the context) then it may be desirable to also [rename the repositories](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository) "Web-Map-Custom-Element" to e.g. "MapML-Polyfill" and "web-map-doc" to e.g. "mapml-viewer-docs", but we can perhaps decide on that later.

**Comment by prushforth** [comment]
I agree a bit of consolidation would be good.  I guess I would go with MapML Viewer to match the proposal and the element.  I think we might get to this in the Jan-Mar 2022 timeframe if things go well.   There is some resistance to "MapML", but it's too late to change at this stage: the die is cast.

**Comment by Malvoz** [comment]
Closing in favor of https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/964.
