### ISSUE TITLE
TPAC 2019

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/chat#7]
@Malvoz, and anyone else on this repo: are you by any chance going to TPAC 2019?  We plan to have a community group [face-to-face meeting](https://www.w3.org/2019/09/TPAC/schedule.html#cgs-fri) there, and you (plural) are very welcome to join us there.  I will post a (draft) agenda to the CG mailing list sometime soon.

**Comment by Malvoz** [comment]
I wont be able to attend, unfortunately. And with my limited knowledge of maps (despite my interest in this CG) I perhaps wouldn't be able to engage much even if I could attend.

Good luck to everybody else going!

**Comment by Malvoz** [comment]
@prushforth are there meeting minutes to be published?

**Comment by Malvoz** [comment]
Found 'em!

https://www.w3.org/2019/09/19-m4h-minutes.html

**Comment by prushforth** [comment]
Yes, not very good minutes, as I was the rookie scribe.

**Comment by Malvoz** [comment]
It's very useful Peter, I appreciate it a lot - thanks! :)

**Comment by Malvoz** [comment]
Time to close this, we may want to link to this event in the index at https://maps4html.org per https://github.com/Maps4HTML/Maps4HTML.github.io/issues/10.
