### ISSUE TITLE
Smashing Conference NY - The Web We Want

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/chat#9]
Hi @nchan0154 and @Malvoz : Stephanie from Smashing Conference contacted me and asked if we were going to be at Smashing Conference NY next week to present our Web We Want submission.

If not, we can submit a 5 minute narrated presentation or video with our Want.  

I wrote a [script](https://docs.google.com/document/d/1FedRupbrwe5tC6iBUBVKVOJa87viN7PDyUMtWnVW_zQ/edit?usp=sharing) proposal.  Can you comment, and if it doesn't misrepresent your want let me know.  The deadline for a submission is Monday, and I'll be away staring tomorrow so it needs some attention as soon as you can, if possible.  Thanks!!!!

**Comment by prushforth** [comment]
This was Stephanie's email:

Hi Peter! 

I wanted to follow up with you in regards to your submission for the Web We Want, https://webwewant.fyi/wants/61/.  Smashing Conference NYC is next week and we will be running a lunch session to cover some of the things submitted to our website.

I wanted to confirm if you’ll be at the event next week and if you’d be interested in preparing a short 2-5 minute lightning presentation about the “want” you submitted. This will be in front of about 30 people, not the whole conference audience. 

The other option would be pre-recording a pitch we could play at the event. It should be 5 min or less and could be as simple as you talking your laptop camera or you could voiceover a brief slide deck.

If you decide to participate, we’d need your slides sent to us by noon on Monday PST (the 14th). Alternatively if you’d like to do a pre-recording, please send us a link to the recording uploaded to YouTube, etc, by the same time on Monday so we can make sure we’re all set for Tuesday at lunch.

Please let me know ASAP if and how you’d like to participate.  If you’re not interested, no big deal; we can present your idea on your behalf. Who knows, you might win something!

**Comment by Malvoz** [comment]
LGTM.

**Comment by prushforth** [comment]
@nchan0154 Hi Nic,

I was wondering if you would be willing to record the narrative?  As @AmeliaBR pointed out, sometimes it's good to (actually) hear other people's voices on this issue.  I believe this might be acceptable to @AmeliaBR (maybe just confirm with her before deciding).

I will keep an eye on this issue, but I will be on a thin connection to the internet until Sunday night.  If we can get a recording 'in the can' by then, I will put it to a video on Sunday night / Monday morning and submit.  

So you'll have to make editorial decisions about the narrative mostly without my input, but that's cool you already have a pretty good notion of what I want :-) in the google doc.  If all that's not possible, I'll just record the script myself, and put it to a video/presentation and hope for the best result.

**Comment by nchan0154** [comment]
While I'm sure everyone would appreciate a recording of me yelling "BUILD LEAFLET INTO THE BROWSER, YOU COWARDS!", I am told I have the worst recording setup and I fear I would sound like I'm underwater and ruin the script 😂

**Comment by prushforth** [comment]
Lol no problem! I will do my best, probably not including that bit.

Cheers
Peter

**Comment by AmeliaBR** [comment]
OK, Peter, I had a go at it. Feel free to take some or all of the suggestions. I cut out or re-worded some of the jargon-y bits, and did a lot of shuffling pieces around, trying to clearly state and separate both the benefits to authors and the benefits to users. Then I added a section at the end based on your other presentation, expanding on the cake metaphor (maybe too much???) while also emphasizing the "your governments already paid for these maps" angle.

And yes, I dropped the "you cowards" bit. As I said on Friday, that's too easy to offend people. Even if they get the reference, the joke could easily fall flat.

**Comment by prushforth** [comment]
Hi @AmeliaBR, @nchan0154 and @Malvoz 

Here is the [result](https://youtu.be/-6-aJAqWWVg).  It was a pretty much one take affair, so the visuals don't match very well with the narration.  Anyway I think the script was pretty good, thanks everyone for your contributions.

Fingers crossed it resonates with people at the conference.

Cheers,
Peter

**Comment by Malvoz** [comment]
Time to close this, we may want to link to this event in the index at https://maps4html.org per https://github.com/Maps4HTML/Maps4HTML.github.io/issues/10.
